dist: trusty
sudo: false
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
addons:
    apt:
      sources:
        - llvm-toolchain-precise-3.7
        - ubuntu-toolchain-r-test
      packages:
        - clang-3.7
        - g++-5
        - gcc-5
        - doxygen
        - graphviz
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - echo "f3546812c11ce7f5d64dc132a566b749 *cmake-3.3.2-Linux-x86_64.tar.gz" > cmake_md5.txt
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
  - md5sum -c cmake_md5.txt
  - tar -xvf cmake-3.3.2-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.3.2-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - which cmake
before_script:
  - cd ${TRAVIS_BUILD_DIR}/test
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
script:
  - cmake .
  - make
  - ./bin/run_tests
after_failure:
  - cat /home/travis/build/libundo/libundo/test/CMakeFiles/CMakeOutput.log
