# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.8.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.8.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Joseph/Documents/Programming/C++/libundo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Joseph/Documents/Programming/C++/libundo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.8.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.8.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.8.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Joseph/Documents/Programming/C++/libundo/CMakeFiles /Users/Joseph/Documents/Programming/C++/libundo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Joseph/Documents/Programming/C++/libundo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named doxygen-doc

# Build rule for target.
doxygen-doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen-doc
.PHONY : doxygen-doc

# fast build rule for target.
doxygen-doc/fast:
	$(MAKE) -f CMakeFiles/doxygen-doc.dir/build.make CMakeFiles/doxygen-doc.dir/build
.PHONY : doxygen-doc/fast

#=============================================================================
# Target rules for targets named libundo

# Build rule for target.
libundo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libundo
.PHONY : libundo

# fast build rule for target.
libundo/fast:
	$(MAKE) -f CMakeFiles/libundo.dir/build.make CMakeFiles/libundo.dir/build
.PHONY : libundo/fast

#=============================================================================
# Target rules for targets named Catch-External

# Build rule for target.
Catch-External: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Catch-External
.PHONY : Catch-External

# fast build rule for target.
Catch-External/fast:
	$(MAKE) -f CMakeFiles/Catch-External.dir/build.make CMakeFiles/Catch-External.dir/build
.PHONY : Catch-External/fast

src/libundo.o: src/libundo.cc.o

.PHONY : src/libundo.o

# target to build an object file
src/libundo.cc.o:
	$(MAKE) -f CMakeFiles/libundo.dir/build.make CMakeFiles/libundo.dir/src/libundo.cc.o
.PHONY : src/libundo.cc.o

src/libundo.i: src/libundo.cc.i

.PHONY : src/libundo.i

# target to preprocess a source file
src/libundo.cc.i:
	$(MAKE) -f CMakeFiles/libundo.dir/build.make CMakeFiles/libundo.dir/src/libundo.cc.i
.PHONY : src/libundo.cc.i

src/libundo.s: src/libundo.cc.s

.PHONY : src/libundo.s

# target to generate assembly for a file
src/libundo.cc.s:
	$(MAKE) -f CMakeFiles/libundo.dir/build.make CMakeFiles/libundo.dir/src/libundo.cc.s
.PHONY : src/libundo.cc.s

test/TestBase.o: test/TestBase.cc.o

.PHONY : test/TestBase.o

# target to build an object file
test/TestBase.cc.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/TestBase.cc.o
.PHONY : test/TestBase.cc.o

test/TestBase.i: test/TestBase.cc.i

.PHONY : test/TestBase.i

# target to preprocess a source file
test/TestBase.cc.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/TestBase.cc.i
.PHONY : test/TestBase.cc.i

test/TestBase.s: test/TestBase.cc.s

.PHONY : test/TestBase.s

# target to generate assembly for a file
test/TestBase.cc.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/TestBase.cc.s
.PHONY : test/TestBase.cc.s

test/TestFile.o: test/TestFile.cc.o

.PHONY : test/TestFile.o

# target to build an object file
test/TestFile.cc.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/TestFile.cc.o
.PHONY : test/TestFile.cc.o

test/TestFile.i: test/TestFile.cc.i

.PHONY : test/TestFile.i

# target to preprocess a source file
test/TestFile.cc.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/TestFile.cc.i
.PHONY : test/TestFile.cc.i

test/TestFile.s: test/TestFile.cc.s

.PHONY : test/TestFile.s

# target to generate assembly for a file
test/TestFile.cc.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/TestFile.cc.s
.PHONY : test/TestFile.cc.s

test/TestTree.o: test/TestTree.cc.o

.PHONY : test/TestTree.o

# target to build an object file
test/TestTree.cc.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/TestTree.cc.o
.PHONY : test/TestTree.cc.o

test/TestTree.i: test/TestTree.cc.i

.PHONY : test/TestTree.i

# target to preprocess a source file
test/TestTree.cc.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/TestTree.cc.i
.PHONY : test/TestTree.cc.i

test/TestTree.s: test/TestTree.cc.s

.PHONY : test/TestTree.s

# target to generate assembly for a file
test/TestTree.cc.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/TestTree.cc.s
.PHONY : test/TestTree.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... run_tests"
	@echo "... doxygen-doc"
	@echo "... rebuild_cache"
	@echo "... libundo"
	@echo "... Catch-External"
	@echo "... src/libundo.o"
	@echo "... src/libundo.i"
	@echo "... src/libundo.s"
	@echo "... test/TestBase.o"
	@echo "... test/TestBase.i"
	@echo "... test/TestBase.s"
	@echo "... test/TestFile.o"
	@echo "... test/TestFile.i"
	@echo "... test/TestFile.s"
	@echo "... test/TestTree.o"
	@echo "... test/TestTree.i"
	@echo "... test/TestTree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

